### ISSUE TITLE
Update "Applications of IPFS" issues with reference info

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/team-mgmt#451]
# Current Situation

In early April some of us generated a bunch of reference info for the "[various applications of ipfs](https://github.com/ipfs/ipfs/labels/applications%20of%20ipfs)" issues but I don't think all of that info found its way back into the issues. The notes are in https://hackmd.io/GYFgrAxhBM0IwFoDMA2AhmhI4oKYIE4xowEAGAlMgI2GsjKWqA==

Some of the issues have gotten a trickle of conversation and we've even gotten one new suggestion from a community member (see https://github.com/ipfs/ipfs/issues/230#issuecomment-300187187).

The ipfs/ipfs repo has hundreds of subscribers, so we want to keep the signal/noise ratio high. By default, those subscribers get notified about every comment on any of these issues, so we want to make sure the comments are mainly _informative_. Open discussions should happen on discuss.ipfs.io

## Goal
Update the "[various applications of ipfs](https://github.com/ipfs/ipfs/labels/applications%20of%20ipfs)" issues so 
* they are informative
* they redirect people to the most constructive ways of engaging
* (ideally) they can gradually accumulate info and suggestions with minimal effort/maintenance

## Completion State for this Work
- [ ] All of the notes from https://hackmd.io/GYFgrAxhBM0IwFoDMA2AhmhI4oKYIE4xowEAGAlMgI2GsjKWqA== are in the corresponding Issue
- [ ] The [main issue](https://github.com/ipfs/ipfs/issues/230) includes info about how to suggest new applications of ipfs
- [ ] The [main issue](https://github.com/ipfs/ipfs/issues/230) includes info about what kind of info we want people to add to these issues, and how to add it (comment).
- [ ] All of the issues have a link back to the [main issue](https://github.com/ipfs/ipfs/issues/230) telling people to look there to learn how to use and add to these issues.
- [ ] All of the issues have a note encouraging people to discuss these topics on discuss.ipfs.io. [We might even want to make a thread for each of them, though empty threads make the forum feel empty/abandoned...]

**Comment by flyingzumwalt** [comment]
Seems like we might see a cascade of ideas coming into those issues. Another good suggestion: https://github.com/ipfs/ipfs/issues/230#issuecomment-300240211

**Comment by flyingzumwalt** [comment]
@empaempa  @DevonJames @Beanow thanks for commenting on https://github.com/ipfs/ipfs/issues/230! I'm really glad to see the issues gathering suggestions like yours. Based on the info above, do you have any suggestions of the best ways for us to encourage more participation by people like you without flooding that particular repository's followers with notifications?

**Comment by Beanow** [comment]
To give you an idea, I found out about IPFS today. As I was wrapping my head around how it works I had already come across github, saw lots of activity and was happy with that as it's a comfortable platform for me.

Normally I would be reluctant to comment with mere theories and ideas when I have only just grasped the basic properties of the protocol a short while before. Instead I searched for it to see if it had already been brought up or even implemented. Which was when I found one of many "applications of ipfs" issues and you literally asked for it to get just an idea from me before fleshing it out.

So for part one of your question, I was definitely encouraged :+1:.
- Low friction getting on GitHub.
- IPFS tackles important problems with elegant approaches. Making it worth getting involved with.

Then there is the flooding part. I'm not familiar with the policy you have in place or what the community is like yet.

But if managing flooding is a real issue for the project I say try not to over-engineer it and apply basic moderation. Have a policy that is tailored to this project and community that can be summed up in as few sentences as possible and have a few moderators that enforce it if need be. The simpler the better, as it will be easier to find, comprehensive and will need less interventions overall.

**Comment by empaempa** [comment]
@flyingzumwalt Thanks for asking! Just as @Beanow I'm quite new to ipfs and commented here as I didn't find any other obvious place. The discuss.ipfs.io sure looks like the right place to ask. I would recommend putting the link in the very top of the readme of https://github.com/ipfs/ipfs : 

> Welcome to IPFS! Why not watch a video demo to get started? Please post questions and ideas at http://discuss.ipfs.io

Keep up the great work!
